#!/usr/bin/env bash

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

fin init-lefthook 1.3.8 "Linux"
echo
fin scaffold-site
echo
fin root-composer install
echo
fin site-composer install
echo
